volumes:
  postgres_data:
    driver: local
  designer_obj_repo:
    driver: local
  local_files:
    driver: local
  grafana:
    driver: local
  prometheus:
    driver: local
  loki:
    driver: local

services:
  hetida-designer-frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    network_mode: host
    ports:
      - 4200:4200

  alternative-backend-opentelemetry:
    image: grafana/otel-lgtm
    network_mode: host
    ports:
      - 4317:4317
      - 4318:4318
      - 3000:3000
    environment:
      - ENABLE_LOGS_TEMPO=true
      - OTEL_METRIC_EXPORT_INTERVAL=500
      - GF_PATHS_DATA=/data/grafana
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4318
    volumes:
      - grafana:/data/grafana
      - prometheus:/data/prometheus
      - loki:/data/loki

  hetida-designer-db:
    image: postgres:latest
    network_mode: host
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: hetida_designer_db
      POSTGRES_USER: hetida_designer_dbuser
      POSTGRES_PASSWORD: hetida_designer_dbpasswd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hetida_designer_dbuser -d hetida_designer_db"]
      interval: 5s
      timeout: 5s
      retries: 5
